name: "Run code checks"

on:
  push:
    branches: [ master, main, codechecking ]
  pull_request:
    branches: [ master, main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - uses: dym-ok/pre-commit-action@v1
      # continue-on-error: true

  ruff:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: lint with ruff
      run: |
        pip install ruff
        ruff check --output-format=github .
        ruff format .
        ruff --output-format=github .
      # continue-on-error: true

  mypy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'

    - name: type check with mypy
      run: |
        pip install mypy
        mypy --strict  shroom_classifier/
      continue-on-error: true
