name: "Run code checks"

on:
  push:
    branches: [ master, main, codechecking ]
  pull_request:
    branches: [ master, main ]

jobs:
  ruff:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: lint with ruff
      run: |
        pip install ruff
        ruff check --output-format=github .
        ruff format .
        ruff --output-format=github .
      # continue-on-error: true

  mypy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
        cache: 'pip'

    - name: type check with mypy
      run: |
        pip install mypy
        pip install -r requirements.txt
        mypy --strict  src/
      #continue-on-error: true
